# Generated by Django 5.0.1 on 2024-01-29 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="regdata",
            new_name="regdate",
        ),
    ]
